--liquibase formatted sql
--changeset maksim.boiko@tsumakov.com:01-slots.sql runOnChange:true

CREATE TABLE IF NOT EXISTS slots
(
  id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  status             TEXT NOT NULL,
  service            TEXT NOT NULL,
  start_time         timestamptz NOT NULL,
  end_time           timestamptz NOT NULL
);

COMMENT ON TABLE slots IS 'A slot of time on a schedule that may be available for booking appointments.';
COMMENT ON COLUMN slots.status IS 'Status of the slot (busy, free)';
COMMENT ON COLUMN slots.service IS 'Categorization of the service that is to be performed during an appointment (dental, gp, mental-health).';
COMMENT ON COLUMN slots.start_time IS 'Date and time of slot to begin.';
COMMENT ON COLUMN slots.end_time IS 'Date and time of slot to end.';

ALTER TABLE slots
ADD CONSTRAINT chk_slots_start_before_end CHECK (start_time < end_time);