package dev.tsumakov.appointments.slot;

import dev.tsumakov.appointments.service.ServiceCategory;
import dev.tsumakov.appointments.slot.exception.SlotIsTakenException;
import dev.tsumakov.appointments.slot.exception.SlotValidationException;
import dev.tsumakov.appointments.slot.status.SlotStatus;
import jakarta.annotation.Nullable;
import java.time.OffsetDateTime;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

@Getter
@ToString
@Builder(access = AccessLevel.PACKAGE)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public final class Slot {

  @EqualsAndHashCode.Include
  @Nullable // Generated by default inside database
  private Long id;
  private SlotStatus status;
  private ServiceCategory service;
  private OffsetDateTime startTime;
  private OffsetDateTime endTime;

  public boolean isFree() {
    return this.status == SlotStatus.FREE;
  }

  public boolean isExpired() {
    return this.endTime.isBefore(OffsetDateTime.now());
  }

  public boolean isBooked() {
    return this.status == SlotStatus.BOOKED;
  }

  public boolean isBlocked() {
    return this.status == SlotStatus.BLOCKED;
  }

  public void markAsBooked() throws SlotIsTakenException {
    checkCanBeChanged();
    this.status = SlotStatus.BOOKED;
  }

  public void markAsFree() throws SlotValidationException {
    if (isBlocked()) {
      throw new SlotValidationException("Can't change status for a blocked slot");
    }
    this.status = SlotStatus.FREE;
  }

  public void validateNotExpired() throws SlotValidationException {
    if (isExpired()) {
      throw new SlotValidationException("Slot is expired");
    }
  }

  private void checkCanBeChanged() throws SlotIsTakenException {
    if (isBooked()) {
      throw new SlotIsTakenException("The slot is already booked");
    }
    if (isBlocked()) {
      throw new SlotIsTakenException("Can't change status for a blocked slot");
    }
  }

}
