--liquibase formatted sql
--changeset maksim.boiko@tsumakov.com:01-slots.sql runOnChange:true

CREATE TABLE IF NOT EXISTS slot
(
  id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  status             TEXT NOT NULL,
  service            TEXT NOT NULL,
  start_time         timestamptz NOT NULL,
  end_time           timestamptz NOT NULL
);

COMMENT ON TABLE slot IS 'A slot of time on a schedule that may be available for booking appointments.';
COMMENT ON COLUMN slot.status IS 'Status of the slot (busy, free)';
COMMENT ON COLUMN slot.service IS 'Categorization of the service that is to be performed during an appointment (dental, gp, mental-health).';
COMMENT ON COLUMN slot.start_time IS 'Date and time of slot to begin.';
COMMENT ON COLUMN slot.end_time IS 'Date and time of slot to end.';
